#!/bin/bash

case "$1" in
01)
  CID=01
  IP=172.18.27.11
  ;;
02)
  CID=02
  IP=172.18.27.12
  ;;
03)
  CID=03
  IP=172.18.27.13
  ;;
*)
  exit -1
esac

docker kill cassie${CID}
echo "Waiting for process to end."
while [ `docker ps -f name=cassie${CID} -q | wc -l` -gt 0 ]; do
  echo -n .
  sleep 1
done
docker rm cassie${CID}
