#!/bin/bash

case "$1" in
01)
  CID=01
  IP=172.18.27.11
  ;;
02)
  CID=02
  IP=172.18.27.12
  ;;
03)
  CID=03
  IP=172.18.27.13
  ;;
*)
  echo "Must specify $NODE where $NODE is [01|02|03]"
  exit -1
esac

shift

exec docker exec -it cassie${CID} /usr/bin/nodetool $@
